// Test to help out with query from "wichtl" on Drools user list:
//     "rules not being reconsidered after modify"

package de.DroolsGUI.adipositasRules

rule "Wenn der BMI des Patienten >= 18.5 und < 25 ist, dann gehšrt der Patient der Kategorie 'Normalgewicht' an und hat ein 'durchschnittliches' Risiko fŸr Begleiterkrankungen des †bergewichts"
	no-loop
when
	MessdatenVonPatient($patient : patient && (getMessdaten().getBmi() >= 18.5) && (getMessdaten().getBmi() < 25))
	$krankheitsbildVonPatient : KrankheitsbildVonPatient(
		patient == $patient
	)
then
	modify( $krankheitsbildVonPatient ) {
		getKrankheitsbild().setAdipositasGrad("Normalgewicht"),
		getKrankheitsbild().setRisikoBegleiterkrankungGrad(1)
	}
end


rule "Wenn Patient der Kategorie 'Normalgewicht' angehoert, dann werden folgende Ma§nahmen vorgeschlagen"
when
	KrankheitsbildVonPatient($patient : patient, krankheitsbild.adipositasGrad == "Normalgewicht")
then
	System.out.println("Some Text");
end


rule "Insert test facts"
    	no-loop
when
    // whenever...
then
    Patient patient = new Patient();
    patient.setName("Frank");
    
    Messdaten messdaten = new Messdaten();
    messdaten.setBmi(19.9);
    
    MessdatenVonPatient mvp = new MessdatenVonPatient();
    mvp.setPatient(patient);
    mvp.setMessdaten(messdaten);
    insert(mvp);
    
    KrankheitsbildVonPatient kvp = new KrankheitsbildVonPatient();
    kvp.setPatient(patient);
    kvp.setKrankheitsbild(new Krankheitsbild());
    insert(kvp);
end


declare Patient
	name : String @key
	geschlecht : String @key
end

declare KrankheitsbildVonPatient
	patient : Patient
	krankheitsbild : Krankheitsbild
end

declare Krankheitsbild
	abdominaleAdipositas : boolean
	adipositasGrad : String
	risikoBegleiterkrankungGrad : int
	risikoMetabolischeKardiovaskulaereKomplikationen : String
	metabolischesSyndrom : boolean
end

declare MessdatenVonPatient
	patient : Patient
	messdaten : Messdaten
end

declare Messdaten
	gewichtInKg : double @key
	groesseInMeter : double @key
	taillenUmfang : double @key
	triglyzeride : int @key
	hdl_cholesterin : int @key
	nuechternblutglukose : int @key
	blutdruck : int	@key	//systolischer Blutdruck / oberer Blutdruck
	bmi : double
end